name: ci.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Java 21
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build with Gardle
      run: ./gradlew build

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Java 21
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 21
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test with Gradle
      run: ./gradlew test
